### ISSUE TITLE
Support the AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by io41** [flomotlik/awsinfo#30]
The `aws` cli tool allows one to specify what profile from `~/.aws/credentials` to use by using `AWS_PROFILE=name-of-profile`, rather than having to pass explicit access key IDs. It would be great if `awsinfo` (via whalebrew) supported the same.

**Comment by io41** [comment]
As a work around, I'm using `AWS_DEFAULT_PROFILE` :)

**Comment by flomotlik** [comment]
@io41 thanks for reporting, fixed and released.

**Comment by io41** [comment]
@flomotlik wow, that was fast. I've tried the lastest (see below) just now, but it doesn't appear to be working...

```$ docker pull flomotlik/awsinfo:latest
latest: Pulling from flomotlik/awsinfo
Digest: sha256:7cd9f140e55b7f69d29dc795e32c5cb0d32782c748bc933f1c0e8580b24e4fed
Status: Image is up to date for flomotlik/awsinfo:latest
[tim:~] $
$ AWS_PROFILE=dev awsinfo route53
Unable to locate credentials. You can configure credentials by running "aws configure".
[tim:~] $
$ AWS_DEFAULT_PROFILE=dev awsinfo route53
-------------------------------------------------------------------------------------
|                                  ListHostedZones                                  |
+-----------------------+------------------------------+------------+---------------+
|        1.Name         |            2.Id              | 3.Private  | 4.RecordSets  |
+-----------------------+------------------------------+------------+---------------+
...```

**Comment by flomotlik** [comment]
You have to reinstall with whalebrew otherwise the new environment variable
doesn't get picked up. Reinstall with force option.

best,
Flo

**Comment by io41** [comment]
Awesome, thank you
