### ISSUE TITLE
Profile flag for viewing info across accounts

### ISSUE THREAD

**Issue by davetownsend** [flomotlik/awsinfo#44]
Any plans to support a `--profile and/or -P` flag?  

Would be great to do `awsinfo lambda -P prod` for example to quickly view info across different aws accounts using the profiles in `~/.aws/credentials`.

**Comment by flomotlik** [comment]
Thats already possible, you can do `awsinfo me --profile someprofile`. `--profile` and `--region` are both supported. Need to check the docs to make that clear.

**Comment by davetownsend** [comment]
For me, `--profile` only seems to only work for `awsinfo me` when I use for anything else, I first get prompted:  
```
You must specify a region. You can also configure your region by running "aws configure".
```
(region already configured for all profiles)

after entering the region, e.g.:
`awsinfo lambda --profile dev --region us-west-2`

it returns the default profile data not the dev profile data.

Any suggestions?

**Comment by davetownsend** [comment]
adding profile to the custom profiles fixed.  

e.g.

```
[default]
region = us-west-2
output = json

[profile devProfile]
region = us-west-2
output = json
```
thanks
