### ISSUE TITLE
AssumeRole and sts

### ISSUE THREAD

**Issue by goosefraba** [flomotlik/awsinfo#79]
Hey thanks for the good work so far!

In your example video, you describe how to use sts to assume a role and use awsinfo for a subaccount. But it seems sts command is not included at all?
How would I assume a role and query stuff for a sub account then?

**Comment by flomotlik** [comment]
Hi, it was moved to the Assume Command: https://github.com/flomotlik/awsinfo/tree/master/scripts/commands/assume

There is also assume role for assuming a specific role and assume token for getting a token with MFA. Hope this helps. Need to update the video

**Comment by goosefraba** [comment]
Yep works like a charm. Thx for clarification - was confused because of the video and didn't check the other commands 🙈

**Comment by flomotlik** [comment]
Yeah I'm constantly updating the commands, so definitely pays off to regularly pull the latest container and check the docs. I need to start promoting this more in the future, but now that the tool suite is more comprehensive that is coming.
